// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// DiscordGuildsColumns holds the columns for the "discord_guilds" table.
	DiscordGuildsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "discord_id", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString},
		{Name: "icon", Type: field.TypeString, Nullable: true},
		{Name: "banner", Type: field.TypeString, Nullable: true},
		{Name: "permissions", Type: field.TypeString},
		{Name: "joined_at", Type: field.TypeTime},
	}
	// DiscordGuildsTable holds the schema information for the "discord_guilds" table.
	DiscordGuildsTable = &schema.Table{
		Name:       "discord_guilds",
		Columns:    DiscordGuildsColumns,
		PrimaryKey: []*schema.Column{DiscordGuildsColumns[0]},
	}
	// DiscordRolesColumns holds the columns for the "discord_roles" table.
	DiscordRolesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "discord_id", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "color", Type: field.TypeString, Nullable: true},
		{Name: "managed", Type: field.TypeBool, Default: false},
		{Name: "discord_guild_roles", Type: field.TypeInt, Nullable: true},
	}
	// DiscordRolesTable holds the schema information for the "discord_roles" table.
	DiscordRolesTable = &schema.Table{
		Name:       "discord_roles",
		Columns:    DiscordRolesColumns,
		PrimaryKey: []*schema.Column{DiscordRolesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "discord_roles_discord_guilds_roles",
				Columns:    []*schema.Column{DiscordRolesColumns[5]},
				RefColumns: []*schema.Column{DiscordGuildsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "age", Type: field.TypeInt},
		{Name: "name", Type: field.TypeString},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		DiscordGuildsTable,
		DiscordRolesTable,
		UsersTable,
	}
)

func init() {
	DiscordRolesTable.ForeignKeys[0].RefTable = DiscordGuildsTable
}
