// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"errors"
	"fmt"
	"math"

	"entgo.io/bug/internal/ent/discordguild"
	"entgo.io/bug/internal/ent/discordrole"
	"entgo.io/bug/internal/ent/predicate"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DiscordGuildQuery is the builder for querying DiscordGuild entities.
type DiscordGuildQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.DiscordGuild
	// eager-loading edges.
	withRoles *DiscordRoleQuery
	modifiers []func(s *sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the DiscordGuildQuery builder.
func (dgq *DiscordGuildQuery) Where(ps ...predicate.DiscordGuild) *DiscordGuildQuery {
	dgq.predicates = append(dgq.predicates, ps...)
	return dgq
}

// Limit adds a limit step to the query.
func (dgq *DiscordGuildQuery) Limit(limit int) *DiscordGuildQuery {
	dgq.limit = &limit
	return dgq
}

// Offset adds an offset step to the query.
func (dgq *DiscordGuildQuery) Offset(offset int) *DiscordGuildQuery {
	dgq.offset = &offset
	return dgq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (dgq *DiscordGuildQuery) Unique(unique bool) *DiscordGuildQuery {
	dgq.unique = &unique
	return dgq
}

// Order adds an order step to the query.
func (dgq *DiscordGuildQuery) Order(o ...OrderFunc) *DiscordGuildQuery {
	dgq.order = append(dgq.order, o...)
	return dgq
}

// QueryRoles chains the current query on the "roles" edge.
func (dgq *DiscordGuildQuery) QueryRoles() *DiscordRoleQuery {
	query := &DiscordRoleQuery{config: dgq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := dgq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := dgq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(discordguild.Table, discordguild.FieldID, selector),
			sqlgraph.To(discordrole.Table, discordrole.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, discordguild.RolesTable, discordguild.RolesColumn),
		)
		fromU = sqlgraph.SetNeighbors(dgq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first DiscordGuild entity from the query.
// Returns a *NotFoundError when no DiscordGuild was found.
func (dgq *DiscordGuildQuery) First(ctx context.Context) (*DiscordGuild, error) {
	nodes, err := dgq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{discordguild.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (dgq *DiscordGuildQuery) FirstX(ctx context.Context) *DiscordGuild {
	node, err := dgq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first DiscordGuild ID from the query.
// Returns a *NotFoundError when no DiscordGuild ID was found.
func (dgq *DiscordGuildQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = dgq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{discordguild.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (dgq *DiscordGuildQuery) FirstIDX(ctx context.Context) int {
	id, err := dgq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single DiscordGuild entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one DiscordGuild entity is not found.
// Returns a *NotFoundError when no DiscordGuild entities are found.
func (dgq *DiscordGuildQuery) Only(ctx context.Context) (*DiscordGuild, error) {
	nodes, err := dgq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{discordguild.Label}
	default:
		return nil, &NotSingularError{discordguild.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (dgq *DiscordGuildQuery) OnlyX(ctx context.Context) *DiscordGuild {
	node, err := dgq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only DiscordGuild ID in the query.
// Returns a *NotSingularError when exactly one DiscordGuild ID is not found.
// Returns a *NotFoundError when no entities are found.
func (dgq *DiscordGuildQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = dgq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{discordguild.Label}
	default:
		err = &NotSingularError{discordguild.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (dgq *DiscordGuildQuery) OnlyIDX(ctx context.Context) int {
	id, err := dgq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of DiscordGuilds.
func (dgq *DiscordGuildQuery) All(ctx context.Context) ([]*DiscordGuild, error) {
	if err := dgq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return dgq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (dgq *DiscordGuildQuery) AllX(ctx context.Context) []*DiscordGuild {
	nodes, err := dgq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of DiscordGuild IDs.
func (dgq *DiscordGuildQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := dgq.Select(discordguild.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (dgq *DiscordGuildQuery) IDsX(ctx context.Context) []int {
	ids, err := dgq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (dgq *DiscordGuildQuery) Count(ctx context.Context) (int, error) {
	if err := dgq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return dgq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (dgq *DiscordGuildQuery) CountX(ctx context.Context) int {
	count, err := dgq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (dgq *DiscordGuildQuery) Exist(ctx context.Context) (bool, error) {
	if err := dgq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return dgq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (dgq *DiscordGuildQuery) ExistX(ctx context.Context) bool {
	exist, err := dgq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the DiscordGuildQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (dgq *DiscordGuildQuery) Clone() *DiscordGuildQuery {
	if dgq == nil {
		return nil
	}
	return &DiscordGuildQuery{
		config:     dgq.config,
		limit:      dgq.limit,
		offset:     dgq.offset,
		order:      append([]OrderFunc{}, dgq.order...),
		predicates: append([]predicate.DiscordGuild{}, dgq.predicates...),
		withRoles:  dgq.withRoles.Clone(),
		// clone intermediate query.
		sql:  dgq.sql.Clone(),
		path: dgq.path,
	}
}

// WithRoles tells the query-builder to eager-load the nodes that are connected to
// the "roles" edge. The optional arguments are used to configure the query builder of the edge.
func (dgq *DiscordGuildQuery) WithRoles(opts ...func(*DiscordRoleQuery)) *DiscordGuildQuery {
	query := &DiscordRoleQuery{config: dgq.config}
	for _, opt := range opts {
		opt(query)
	}
	dgq.withRoles = query
	return dgq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		DiscordID string `json:"discord_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.DiscordGuild.Query().
//		GroupBy(discordguild.FieldDiscordID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (dgq *DiscordGuildQuery) GroupBy(field string, fields ...string) *DiscordGuildGroupBy {
	group := &DiscordGuildGroupBy{config: dgq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := dgq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return dgq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		DiscordID string `json:"discord_id,omitempty"`
//	}
//
//	client.DiscordGuild.Query().
//		Select(discordguild.FieldDiscordID).
//		Scan(ctx, &v)
//
func (dgq *DiscordGuildQuery) Select(fields ...string) *DiscordGuildSelect {
	dgq.fields = append(dgq.fields, fields...)
	return &DiscordGuildSelect{DiscordGuildQuery: dgq}
}

func (dgq *DiscordGuildQuery) prepareQuery(ctx context.Context) error {
	for _, f := range dgq.fields {
		if !discordguild.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if dgq.path != nil {
		prev, err := dgq.path(ctx)
		if err != nil {
			return err
		}
		dgq.sql = prev
	}
	return nil
}

func (dgq *DiscordGuildQuery) sqlAll(ctx context.Context) ([]*DiscordGuild, error) {
	var (
		nodes       = []*DiscordGuild{}
		_spec       = dgq.querySpec()
		loadedTypes = [1]bool{
			dgq.withRoles != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &DiscordGuild{config: dgq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(dgq.modifiers) > 0 {
		_spec.Modifiers = dgq.modifiers
	}
	if err := sqlgraph.QueryNodes(ctx, dgq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}

	if query := dgq.withRoles; query != nil {
		fks := make([]driver.Value, 0, len(nodes))
		nodeids := make(map[int]*DiscordGuild)
		for i := range nodes {
			fks = append(fks, nodes[i].ID)
			nodeids[nodes[i].ID] = nodes[i]
			nodes[i].Edges.Roles = []*DiscordRole{}
		}
		query.withFKs = true
		query.Where(predicate.DiscordRole(func(s *sql.Selector) {
			s.Where(sql.InValues(discordguild.RolesColumn, fks...))
		}))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			fk := n.discord_guild_roles
			if fk == nil {
				return nil, fmt.Errorf(`foreign-key "discord_guild_roles" is nil for node %v`, n.ID)
			}
			node, ok := nodeids[*fk]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "discord_guild_roles" returned %v for node %v`, *fk, n.ID)
			}
			node.Edges.Roles = append(node.Edges.Roles, n)
		}
	}

	return nodes, nil
}

func (dgq *DiscordGuildQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := dgq.querySpec()
	if len(dgq.modifiers) > 0 {
		_spec.Modifiers = dgq.modifiers
	}
	_spec.Node.Columns = dgq.fields
	if len(dgq.fields) > 0 {
		_spec.Unique = dgq.unique != nil && *dgq.unique
	}
	return sqlgraph.CountNodes(ctx, dgq.driver, _spec)
}

func (dgq *DiscordGuildQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := dgq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (dgq *DiscordGuildQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   discordguild.Table,
			Columns: discordguild.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: discordguild.FieldID,
			},
		},
		From:   dgq.sql,
		Unique: true,
	}
	if unique := dgq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := dgq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, discordguild.FieldID)
		for i := range fields {
			if fields[i] != discordguild.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := dgq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := dgq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := dgq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := dgq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (dgq *DiscordGuildQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(dgq.driver.Dialect())
	t1 := builder.Table(discordguild.Table)
	columns := dgq.fields
	if len(columns) == 0 {
		columns = discordguild.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if dgq.sql != nil {
		selector = dgq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if dgq.unique != nil && *dgq.unique {
		selector.Distinct()
	}
	for _, m := range dgq.modifiers {
		m(selector)
	}
	for _, p := range dgq.predicates {
		p(selector)
	}
	for _, p := range dgq.order {
		p(selector)
	}
	if offset := dgq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := dgq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (dgq *DiscordGuildQuery) ForUpdate(opts ...sql.LockOption) *DiscordGuildQuery {
	if dgq.driver.Dialect() == dialect.Postgres {
		dgq.Unique(false)
	}
	dgq.modifiers = append(dgq.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return dgq
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (dgq *DiscordGuildQuery) ForShare(opts ...sql.LockOption) *DiscordGuildQuery {
	if dgq.driver.Dialect() == dialect.Postgres {
		dgq.Unique(false)
	}
	dgq.modifiers = append(dgq.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return dgq
}

// Modify adds a query modifier for attaching custom logic to queries.
func (dgq *DiscordGuildQuery) Modify(modifiers ...func(s *sql.Selector)) *DiscordGuildSelect {
	dgq.modifiers = append(dgq.modifiers, modifiers...)
	return dgq.Select()
}

// DiscordGuildGroupBy is the group-by builder for DiscordGuild entities.
type DiscordGuildGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (dggb *DiscordGuildGroupBy) Aggregate(fns ...AggregateFunc) *DiscordGuildGroupBy {
	dggb.fns = append(dggb.fns, fns...)
	return dggb
}

// Scan applies the group-by query and scans the result into the given value.
func (dggb *DiscordGuildGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := dggb.path(ctx)
	if err != nil {
		return err
	}
	dggb.sql = query
	return dggb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (dggb *DiscordGuildGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := dggb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (dggb *DiscordGuildGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(dggb.fields) > 1 {
		return nil, errors.New("ent: DiscordGuildGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := dggb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (dggb *DiscordGuildGroupBy) StringsX(ctx context.Context) []string {
	v, err := dggb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (dggb *DiscordGuildGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = dggb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{discordguild.Label}
	default:
		err = fmt.Errorf("ent: DiscordGuildGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (dggb *DiscordGuildGroupBy) StringX(ctx context.Context) string {
	v, err := dggb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (dggb *DiscordGuildGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(dggb.fields) > 1 {
		return nil, errors.New("ent: DiscordGuildGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := dggb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (dggb *DiscordGuildGroupBy) IntsX(ctx context.Context) []int {
	v, err := dggb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (dggb *DiscordGuildGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = dggb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{discordguild.Label}
	default:
		err = fmt.Errorf("ent: DiscordGuildGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (dggb *DiscordGuildGroupBy) IntX(ctx context.Context) int {
	v, err := dggb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (dggb *DiscordGuildGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(dggb.fields) > 1 {
		return nil, errors.New("ent: DiscordGuildGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := dggb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (dggb *DiscordGuildGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := dggb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (dggb *DiscordGuildGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = dggb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{discordguild.Label}
	default:
		err = fmt.Errorf("ent: DiscordGuildGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (dggb *DiscordGuildGroupBy) Float64X(ctx context.Context) float64 {
	v, err := dggb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (dggb *DiscordGuildGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(dggb.fields) > 1 {
		return nil, errors.New("ent: DiscordGuildGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := dggb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (dggb *DiscordGuildGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := dggb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (dggb *DiscordGuildGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = dggb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{discordguild.Label}
	default:
		err = fmt.Errorf("ent: DiscordGuildGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (dggb *DiscordGuildGroupBy) BoolX(ctx context.Context) bool {
	v, err := dggb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (dggb *DiscordGuildGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range dggb.fields {
		if !discordguild.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := dggb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := dggb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (dggb *DiscordGuildGroupBy) sqlQuery() *sql.Selector {
	selector := dggb.sql.Select()
	aggregation := make([]string, 0, len(dggb.fns))
	for _, fn := range dggb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(dggb.fields)+len(dggb.fns))
		for _, f := range dggb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(dggb.fields...)...)
}

// DiscordGuildSelect is the builder for selecting fields of DiscordGuild entities.
type DiscordGuildSelect struct {
	*DiscordGuildQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (dgs *DiscordGuildSelect) Scan(ctx context.Context, v interface{}) error {
	if err := dgs.prepareQuery(ctx); err != nil {
		return err
	}
	dgs.sql = dgs.DiscordGuildQuery.sqlQuery(ctx)
	return dgs.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (dgs *DiscordGuildSelect) ScanX(ctx context.Context, v interface{}) {
	if err := dgs.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (dgs *DiscordGuildSelect) Strings(ctx context.Context) ([]string, error) {
	if len(dgs.fields) > 1 {
		return nil, errors.New("ent: DiscordGuildSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := dgs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (dgs *DiscordGuildSelect) StringsX(ctx context.Context) []string {
	v, err := dgs.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (dgs *DiscordGuildSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = dgs.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{discordguild.Label}
	default:
		err = fmt.Errorf("ent: DiscordGuildSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (dgs *DiscordGuildSelect) StringX(ctx context.Context) string {
	v, err := dgs.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (dgs *DiscordGuildSelect) Ints(ctx context.Context) ([]int, error) {
	if len(dgs.fields) > 1 {
		return nil, errors.New("ent: DiscordGuildSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := dgs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (dgs *DiscordGuildSelect) IntsX(ctx context.Context) []int {
	v, err := dgs.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (dgs *DiscordGuildSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = dgs.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{discordguild.Label}
	default:
		err = fmt.Errorf("ent: DiscordGuildSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (dgs *DiscordGuildSelect) IntX(ctx context.Context) int {
	v, err := dgs.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (dgs *DiscordGuildSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(dgs.fields) > 1 {
		return nil, errors.New("ent: DiscordGuildSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := dgs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (dgs *DiscordGuildSelect) Float64sX(ctx context.Context) []float64 {
	v, err := dgs.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (dgs *DiscordGuildSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = dgs.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{discordguild.Label}
	default:
		err = fmt.Errorf("ent: DiscordGuildSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (dgs *DiscordGuildSelect) Float64X(ctx context.Context) float64 {
	v, err := dgs.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (dgs *DiscordGuildSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(dgs.fields) > 1 {
		return nil, errors.New("ent: DiscordGuildSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := dgs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (dgs *DiscordGuildSelect) BoolsX(ctx context.Context) []bool {
	v, err := dgs.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (dgs *DiscordGuildSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = dgs.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{discordguild.Label}
	default:
		err = fmt.Errorf("ent: DiscordGuildSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (dgs *DiscordGuildSelect) BoolX(ctx context.Context) bool {
	v, err := dgs.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (dgs *DiscordGuildSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := dgs.sql.Query()
	if err := dgs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (dgs *DiscordGuildSelect) Modify(modifiers ...func(s *sql.Selector)) *DiscordGuildSelect {
	dgs.modifiers = append(dgs.modifiers, modifiers...)
	return dgs
}
