// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/bug/internal/ent/discordguild"
	"entgo.io/bug/internal/ent/predicate"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DiscordGuildDelete is the builder for deleting a DiscordGuild entity.
type DiscordGuildDelete struct {
	config
	hooks    []Hook
	mutation *DiscordGuildMutation
}

// Where appends a list predicates to the DiscordGuildDelete builder.
func (dgd *DiscordGuildDelete) Where(ps ...predicate.DiscordGuild) *DiscordGuildDelete {
	dgd.mutation.Where(ps...)
	return dgd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (dgd *DiscordGuildDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(dgd.hooks) == 0 {
		affected, err = dgd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*DiscordGuildMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			dgd.mutation = mutation
			affected, err = dgd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(dgd.hooks) - 1; i >= 0; i-- {
			if dgd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = dgd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, dgd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (dgd *DiscordGuildDelete) ExecX(ctx context.Context) int {
	n, err := dgd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (dgd *DiscordGuildDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: discordguild.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: discordguild.FieldID,
			},
		},
	}
	if ps := dgd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, dgd.driver, _spec)
}

// DiscordGuildDeleteOne is the builder for deleting a single DiscordGuild entity.
type DiscordGuildDeleteOne struct {
	dgd *DiscordGuildDelete
}

// Exec executes the deletion query.
func (dgdo *DiscordGuildDeleteOne) Exec(ctx context.Context) error {
	n, err := dgdo.dgd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{discordguild.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (dgdo *DiscordGuildDeleteOne) ExecX(ctx context.Context) {
	dgdo.dgd.ExecX(ctx)
}
