// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/bug/internal/ent/discordrole"
	"entgo.io/bug/internal/ent/predicate"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DiscordRoleDelete is the builder for deleting a DiscordRole entity.
type DiscordRoleDelete struct {
	config
	hooks    []Hook
	mutation *DiscordRoleMutation
}

// Where appends a list predicates to the DiscordRoleDelete builder.
func (drd *DiscordRoleDelete) Where(ps ...predicate.DiscordRole) *DiscordRoleDelete {
	drd.mutation.Where(ps...)
	return drd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (drd *DiscordRoleDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(drd.hooks) == 0 {
		affected, err = drd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*DiscordRoleMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			drd.mutation = mutation
			affected, err = drd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(drd.hooks) - 1; i >= 0; i-- {
			if drd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = drd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, drd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (drd *DiscordRoleDelete) ExecX(ctx context.Context) int {
	n, err := drd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (drd *DiscordRoleDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: discordrole.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: discordrole.FieldID,
			},
		},
	}
	if ps := drd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, drd.driver, _spec)
}

// DiscordRoleDeleteOne is the builder for deleting a single DiscordRole entity.
type DiscordRoleDeleteOne struct {
	drd *DiscordRoleDelete
}

// Exec executes the deletion query.
func (drdo *DiscordRoleDeleteOne) Exec(ctx context.Context) error {
	n, err := drdo.drd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{discordrole.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (drdo *DiscordRoleDeleteOne) ExecX(ctx context.Context) {
	drdo.drd.ExecX(ctx)
}
