// Code generated by entc, DO NOT EDIT.

package ent

import (
	"entgo.io/bug/ent/schema"
	"entgo.io/bug/internal/ent/discordrole"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	discordroleFields := schema.DiscordRole{}.Fields()
	_ = discordroleFields
	// discordroleDescManaged is the schema descriptor for managed field.
	discordroleDescManaged := discordroleFields[3].Descriptor()
	// discordrole.DefaultManaged holds the default value on creation for the managed field.
	discordrole.DefaultManaged = discordroleDescManaged.Default.(bool)
}
