// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// DiscordGuild is the predicate function for discordguild builders.
type DiscordGuild func(*sql.Selector)

// DiscordRole is the predicate function for discordrole builders.
type DiscordRole func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
